CREATE TABLE temperature (
  id SERIAL PRIMARY KEY,
  timestamp TIMESTAMP NOT NULL,
  temperature REAL NOT NULL,
  humidity REAL NOT NULL,
  category VARCHAR(50) NOT NULL
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(50) UNIQUE NOT NULL,
  is_admin BOOLEAN NOT NULL DEFAULT false
);
